// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBAKGYJ4HfwHj2btSHWvqiFVgiDBNR5PY',
    appId: '1:823626278286:web:8ae8b414c9ef5f1add70df',
    messagingSenderId: '823626278286',
    projectId: 'flutter-learning-eb9dd',
    authDomain: 'flutter-learning-eb9dd.firebaseapp.com',
    storageBucket: 'flutter-learning-eb9dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZhfrWVkUegVkCa9c8isP6vYpNSnulQ0',
    appId: '1:823626278286:android:27a623c422309321dd70df',
    messagingSenderId: '823626278286',
    projectId: 'flutter-learning-eb9dd',
    storageBucket: 'flutter-learning-eb9dd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hQN0bHF3Q5816tsBHC3cYocvMYM3lPQ',
    appId: '1:823626278286:ios:36655926a3e987d5dd70df',
    messagingSenderId: '823626278286',
    projectId: 'flutter-learning-eb9dd',
    storageBucket: 'flutter-learning-eb9dd.firebasestorage.app',
    iosBundleId: 'com.example.rpg',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4hQN0bHF3Q5816tsBHC3cYocvMYM3lPQ',
    appId: '1:823626278286:ios:36655926a3e987d5dd70df',
    messagingSenderId: '823626278286',
    projectId: 'flutter-learning-eb9dd',
    storageBucket: 'flutter-learning-eb9dd.firebasestorage.app',
    iosBundleId: 'com.example.rpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBAKGYJ4HfwHj2btSHWvqiFVgiDBNR5PY',
    appId: '1:823626278286:web:0a2c53460904879ddd70df',
    messagingSenderId: '823626278286',
    projectId: 'flutter-learning-eb9dd',
    authDomain: 'flutter-learning-eb9dd.firebaseapp.com',
    storageBucket: 'flutter-learning-eb9dd.firebasestorage.app',
  );
}
